# Generated by Django 3.1.6 on 2024-12-30 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_place', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=5)),
                ('end_place', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
