# Generated by Django 3.1.6 on 2024-12-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnb',
            name='countries',
        ),
        migrations.AddField(
            model_name='airbnb',
            name='countries',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airbnbs', to='country.country'),
            preserve_default=False,
        ),
    ]
