# Generated by Django 3.1.6 on 2024-12-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_auto_20241230_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbnb',
            old_name='countries',
            new_name='country',
        ),
    ]
