# Generated by Django 3.1.6 on 2024-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20241228_1308'),
        ('airbnb', '0003_auto_20241225_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnb',
            name='city',
        ),
        migrations.AddField(
            model_name='airbnb',
            name='city',
            field=models.ManyToManyField(related_name='airbnbs', to='country.Country'),
        ),
    ]
