# Generated by Django 3.1.6 on 2024-12-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0004_auto_20241229_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbnb',
            old_name='city',
            new_name='cities',
        ),
    ]
