# Generated by Django 3.1.6 on 2024-12-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_person', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100)),
                ('gps', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=100, null=True)),
                ('countries', models.ManyToManyField(related_name='activities', to='country.Country')),
            ],
        ),
    ]
