# Generated by Django 3.1.6 on 2024-12-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20241225_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price_person',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
