# Generated by Django 3.1.6 on 2024-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20241228_1308'),
        ('activity', '0004_auto_20241225_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='city',
        ),
        migrations.AddField(
            model_name='activity',
            name='cities',
            field=models.ManyToManyField(related_name='activities', to='country.Country'),
        ),
    ]
