# Generated by Django 3.1.6 on 2024-12-25 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airbnb', '0002_auto_20241225_1345'),
        ('travel', '0002_auto_20241225_1345'),
        ('activity', '0003_auto_20241225_1345'),
        ('expense', '0004_auto_20241225_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(max_length=2)),
                ('place', models.CharField(max_length=100)),
                ('people', models.IntegerField(max_length=3)),
                ('activities', models.ManyToManyField(related_name='activities_list', to='activity.Activity')),
                ('expenses', models.ManyToManyField(related_name='expenses_list', to='expense.Expense')),
                ('housing', models.ManyToManyField(related_name='airbnbs_list', to='airbnb.Airbnb')),
                ('travels', models.ManyToManyField(related_name='travels_list', to='travel.Travel')),
            ],
        ),
    ]
