# Generated by Django 3.1.6 on 2024-12-30 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('country', '0001_initial'),
        ('airbnb', '0001_initial'),
        ('travel', '0003_auto_20241225_1418'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('people', models.IntegerField()),
                ('activities', models.ManyToManyField(related_name='activities_list', to='activity.Activity')),
                ('airbnbs', models.ManyToManyField(related_name='airbnbs_list', to='airbnb.Airbnb')),
                ('expenses', models.ManyToManyField(related_name='expenses_list', to='expense.Expense')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='country.country')),
                ('travels', models.ManyToManyField(related_name='travels_list', to='travel.Travel')),
            ],
        ),
    ]
