# Generated by Django 3.1.6 on 2024-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='people',
            field=models.IntegerField(),
        ),
    ]
