# Generated by Django 3.1.6 on 2024-12-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20241225_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='housing',
            new_name='airbnbs',
        ),
    ]
