# Generated by Django 3.1.6 on 2024-12-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('trip', '0003_auto_20241225_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='country.country'),
        ),
    ]
