# Generated by Django 3.1.6 on 2024-12-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20241228_1308'),
        ('trip', '0004_auto_20241228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='country.country'),
        ),
    ]
