# Generated by Django 3.1.6 on 2024-12-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('category', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=4)),
                ('note', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
